version: '3.4'
networks:
  mynet:
services:
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment: 
      SA_PASSWORD: "Asdf1234!"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S database -U sa -P 'Asdf1234!' -Q 'select 1'
    networks:
      - mynet
    ports:
      - "1433:1433"

  initdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    networks:
      - mynet
    links:
      - database
    depends_on:
      - database
    entrypoint:
      - bash 
      - -c 
      - '/opt/mssql-tools/bin/sqlcmd -S database -U sa -P Asdf1234! -Q "CREATE DATABASE Hangfiredb"'
